// hold the IDs used for the GUI and icon

#define ID_TITLE_LABEL 99

#define ID_NUMFRAMES_LABEL 100
#define ID_NUMFRAMES_TEXTBOX 101
#define ID_ADD_NUMFRAMES 102 

#define ID_DELAY_LABEL 103 
#define ID_DELAY_TEXTBOX 104
#define ID_ADD_DELAY 105

#define ID_SELECT_SCREENAREA_BUTTON 106 
#define ID_START_BUTTON 107

#define ID_PROGRESS_MSG 108

#define IDI_ICON 200